In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/fred_data.csv')

In [3]:
df.head()

,DATE,A067RL1Q156SBEA,A067RL1Q156SBEA_CCA,A067RL1Q156SBEA_CCH,A067RL1Q156SBEA_CH1,A067RL1Q156SBEA_CHG,A067RL1Q156SBEA_LOG,A067RL1Q156SBEA_PC1,A067RL1Q156SBEA_PCA,A067RL1Q156SBEA_PCH,...,PCEC_PCH,TDSP,TDSP_CCA,TDSP_CCH,TDSP_CH1,TDSP_CHG,TDSP_LOG,TDSP_PC1,TDSP_PCA,TDSP_PCH
0,1947-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1947-04-01,-3.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1947-07-01,11.1,NaN,NaN,NaN,14.9,2.4,NaN,7180.4,-392.1,...,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1947-10-01,-5.5,NaN,NaN,NaN,-16.6,NaN,NaN,-94.0,-149.5,...,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1948-01-01,7.7,NaN,NaN,NaN,13.2,2.0,NaN,284.2,-240.0,...,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Clean data
df_rename = df.rename({'DATE':'quarter'}, axis=1)
df_rename.head()

,quarter,A067RL1Q156SBEA,A067RL1Q156SBEA_CCA,A067RL1Q156SBEA_CCH,A067RL1Q156SBEA_CH1,A067RL1Q156SBEA_CHG,A067RL1Q156SBEA_LOG,A067RL1Q156SBEA_PC1,A067RL1Q156SBEA_PCA,A067RL1Q156SBEA_PCH,...,PCEC_PCH,TDSP,TDSP_CCA,TDSP_CCH,TDSP_CH1,TDSP_CHG,TDSP_LOG,TDSP_PC1,TDSP_PCA,TDSP_PCH
0,1947-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1947-04-01,-3.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1947-07-01,11.1,NaN,NaN,NaN,14.9,2.4,NaN,7180.4,-392.1,...,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1947-10-01,-5.5,NaN,NaN,NaN,-16.6,NaN,NaN,-94.0,-149.5,...,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1948-01-01,7.7,NaN,NaN,NaN,13.2,2.0,NaN,284.2,-240.0,...,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Update values in 'quarter' column to have the format: YYYYQ1-4. Example: 1970Q1

def map_quarter(s):
    quarter = ''
    month = s.split('-')[1]
    year = s.split('-')[0]
    
    if month == '01':
        quarter = '1'
    elif month == '04':
        quarter = '2'
    elif month == '07':
        quarter = '3'
    elif month == '10':
        quarter = '4'
        
    x = year + 'Q' + quarter
    
    return x

df_rename['quarter'] = df_rename['quarter'].apply(map_quarter)
df_rename.head()

,quarter,A067RL1Q156SBEA,A067RL1Q156SBEA_CCA,A067RL1Q156SBEA_CCH,A067RL1Q156SBEA_CH1,A067RL1Q156SBEA_CHG,A067RL1Q156SBEA_LOG,A067RL1Q156SBEA_PC1,A067RL1Q156SBEA_PCA,A067RL1Q156SBEA_PCH,...,PCEC_PCH,TDSP,TDSP_CCA,TDSP_CCH,TDSP_CH1,TDSP_CHG,TDSP_LOG,TDSP_PC1,TDSP_PCA,TDSP_PCH
0,1947Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1947Q2,-3.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1947Q3,11.1,NaN,NaN,NaN,14.9,2.4,NaN,7180.4,-392.1,...,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1947Q4,-5.5,NaN,NaN,NaN,-16.6,NaN,NaN,-94.0,-149.5,...,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1948Q1,7.7,NaN,NaN,NaN,13.2,2.0,NaN,284.2,-240.0,...,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_rename.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 100 columns):
quarter                332 non-null object
A067RL1Q156SBEA        289 non-null float64
A067RL1Q156SBEA_CCA    218 non-null float64
A067RL1Q156SBEA_CCH    218 non-null float64
A067RL1Q156SBEA_CH1    285 non-null float64
A067RL1Q156SBEA_CHG    288 non-null float64
A067RL1Q156SBEA_LOG    250 non-null float64
A067RL1Q156SBEA_PC1    285 non-null float64
A067RL1Q156SBEA_PCA    288 non-null float64
A067RL1Q156SBEA_PCH    288 non-null float64
BPCCRO1Q156NBEA        238 non-null float64
BPCCRO1Q156NBEA_CCA    237 non-null float64
BPCCRO1Q156NBEA_CCH    237 non-null float64
BPCCRO1Q156NBEA_CH1    234 non-null float64
BPCCRO1Q156NBEA_CHG    237 non-null float64
BPCCRO1Q156NBEA_LOG    238 non-null float64
BPCCRO1Q156NBEA_PC1    234 non-null float64
BPCCRO1Q156NBEA_PCA    237 non-null float64
BPCCRO1Q156NBEA_PCH    237 non-null float64
CPALTT01USQ659N        238 non-null float64
CPALTT01USQ659N_CCA    230 non-null float64
CPALTT01USQ659N_CCH    230 non-null float64
CPALTT01USQ659N_CH1    234 non-null float64
CPALTT01USQ659N_CHG    237 non-null float64
CPALTT01USQ659N_LOG    233 non-null float64
CPALTT01USQ659N_PC1    234 non-null float64
CPALTT01USQ659N_PCA    237 non-null float64
CPALTT01USQ659N_PCH    237 non-null float64
DPCERO1Q156NBEA        286 non-null float64
DPCERO1Q156NBEA_CCA    261 non-null float64
DPCERO1Q156NBEA_CCH    261 non-null float64
DPCERO1Q156NBEA_CH1    282 non-null float64
DPCERO1Q156NBEA_CHG    285 non-null float64
DPCERO1Q156NBEA_LOG    269 non-null float64
DPCERO1Q156NBEA_PC1    281 non-null float64
DPCERO1Q156NBEA_PCA    284 non-null float64
DPCERO1Q156NBEA_PCH    284 non-null float64
GFDEGDQ188S            214 non-null float64
GFDEGDQ188S_CCA        213 non-null float64
GFDEGDQ188S_CCH        213 non-null float64
GFDEGDQ188S_CH1        210 non-null float64
GFDEGDQ188S_CHG        213 non-null float64
GFDEGDQ188S_LOG        214 non-null float64
GFDEGDQ188S_PC1        210 non-null float64
GFDEGDQ188S_PCA        213 non-null float64
GFDEGDQ188S_PCH        213 non-null float64
GPDI                   290 non-null float64
GPDI_CCA               289 non-null float64
GPDI_CCH               289 non-null float64
GPDI_CH1               286 non-null float64
GPDI_CHG               289 non-null float64
GPDI_LOG               290 non-null float64
GPDI_PC1               286 non-null float64
GPDI_PCA               289 non-null float64
GPDI_PCH               289 non-null float64
M2V                    242 non-null float64
M2V_CCA                241 non-null float64
M2V_CCH                241 non-null float64
M2V_CH1                238 non-null float64
M2V_CHG                241 non-null float64
M2V_LOG                242 non-null float64
M2V_PC1                238 non-null float64
M2V_PCA                241 non-null float64
M2V_PCH                241 non-null float64
MSPUS                  227 non-null float64
MSPUS_CCA              226 non-null float64
MSPUS_CCH              226 non-null float64
MSPUS_CH1              223 non-null float64
MSPUS_CHG              226 non-null float64
MSPUS_LOG              227 non-null float64
MSPUS_PC1              223 non-null float64
MSPUS_PCA              226 non-null float64
MSPUS_PCH              226 non-null float64
NROU                   324 non-null float64
NROU_CCA               323 non-null float64
NROU_CCH               323 non-null float64
NROU_CH1               320 non-null float64
NROU_CHG               323 non-null float64
NROU_LOG               324 non-null float64
NROU_PC1               320 non-null float64
NROU_PCA               323 non-null float64
NROU_PCH               323 non-null float64
PCEC                   290 non-null float64
PCEC_CCA               289 non-null float64
PCEC_CCH               289 non-null float64
PCEC_CH1               286 non-null float64
PCEC_CHG               289 non-null float64
PCEC_LOG               290 non-null float64
PCEC_PC1               286 non-null float64
PCEC_PCA               289 non-null float64
PCEC_PCH               289 non-null float64
TDSP                   158 non-null float64
TDSP_CCA               157 non-null float64
TDSP_CCH               157 non-null float64
TDSP_CH1               154 non-null float64
TDSP_CHG               157 non-null float64
TDSP_LOG               158 non-null float64
TDSP_PC1               154 non-null float64
TDSP_PCA               157 non-null float64
TDSP_PCH               157 non-null float64
dtypes: float64(99), object(1)
memory usage: 259.5+ KB

In [7]:
rename_map = {'A067RL1Q156SBEA':'real_disp_pers_inc',
'A067RL1Q156SBEA_CHG':'real_disp_pers_inc_CHG',
'A067RL1Q156SBEA_CH1':'real_disp_pers_inc_CH1',
'A067RL1Q156SBEA_PCH':'real_disp_pers_inc_PCH',
'A067RL1Q156SBEA_PC1':'real_disp_pers_inc_PC1',
'A067RL1Q156SBEA_PCA':'real_disp_pers_inc_PCA',
'A067RL1Q156SBEA_CCH':'real_disp_pers_inc_CCH',
'A067RL1Q156SBEA_CCA':'real_disp_pers_inc_CCA',
'A067RL1Q156SBEA_LOG':'real_disp_pers_inc_LOG',
'BPCCRO1Q156NBEA':'personal_consumption_exp_excl_food_energy',
'BPCCRO1Q156NBEA_CHG':'personal_consumption_exp_excl_food_energy_CHG',
'BPCCRO1Q156NBEA_CH1':'personal_consumption_exp_excl_food_energy_CH1',
'BPCCRO1Q156NBEA_PCH':'personal_consumption_exp_excl_food_energy_PCH',
'BPCCRO1Q156NBEA_PC1':'personal_consumption_exp_excl_food_energy_PC1',
'BPCCRO1Q156NBEA_PCA':'personal_consumption_exp_excl_food_energy_PCA',
'BPCCRO1Q156NBEA_CCH':'personal_consumption_exp_excl_food_energy_CCH',
'BPCCRO1Q156NBEA_CCA':'personal_consumption_exp_excl_food_energy_CCA',
'BPCCRO1Q156NBEA_LOG':'personal_consumption_exp_excl_food_energy_LOG',
'CPALTT01USQ659N':'cpi_US_total',
'CPALTT01USQ659N_CHG':'cpi_US_total_CHG',
'CPALTT01USQ659N_CH1':'cpi_US_total_CH1',
'CPALTT01USQ659N_PCH':'cpi_US_total_PCH',
'CPALTT01USQ659N_PC1':'cpi_US_total_PC1',
'CPALTT01USQ659N_PCA':'cpi_US_total_PCA',
'CPALTT01USQ659N_CCH':'cpi_US_total_CCH',
'CPALTT01USQ659N_CCA':'cpi_US_total_CCA',
'CPALTT01USQ659N_LOG':'cpi_US_total_LOG',
'GFDEGDQ188S':'tot_public_debt_as_pct_of_gdp',
'GFDEGDQ188S_CHG':'tot_public_debt_as_pct_of_gdp_CHG',
'GFDEGDQ188S_CH1':'tot_public_debt_as_pct_of_gdp_CH1',
'GFDEGDQ188S_PCH':'tot_public_debt_as_pct_of_gdp_PCH',
'GFDEGDQ188S_PC1':'tot_public_debt_as_pct_of_gdp_PC1',
'GFDEGDQ188S_PCA':'tot_public_debt_as_pct_of_gdp_PCA',
'GFDEGDQ188S_CCH':'tot_public_debt_as_pct_of_gdp_CCH',
'GFDEGDQ188S_CCA':'tot_public_debt_as_pct_of_gdp_CCA',
'GFDEGDQ188S_LOG':'tot_public_debt_as_pct_of_gdp_LOG',
'GPDI':'gross_private_domestic_invest',
'GPDI_CHG':'gross_private_domestic_invest_CHG',
'GPDI_CH1':'gross_private_domestic_invest_CH1',
'GPDI_PCH':'gross_private_domestic_invest_PCH',
'GPDI_PC1':'gross_private_domestic_invest_PC1',
'GPDI_PCA':'gross_private_domestic_invest_PCA',
'GPDI_CCH':'gross_private_domestic_invest_CCH',
'GPDI_CCA':'gross_private_domestic_invest_CCA',
'GPDI_LOG':'gross_private_domestic_invest_LOG',
'M2V':'M2_velocity',
'M2V_CHG':'M2_velocity_CHG',
'M2V_CH1':'M2_velocity_CH1',
'M2V_PCH':'M2_velocity_PCH',
'M2V_PC1':'M2_velocity_PC1',
'M2V_PCA':'M2_velocity_PCA',
'M2V_CCH':'M2_velocity_CCH',
'M2V_CCA':'M2_velocity_CCA',
'M2V_LOG':'M2_velocity_LOG',
'MSPUS':'median_sls_price_houses_sold_US',
'MSPUS_CHG':'median_sls_price_houses_sold_US_CHG',
'MSPUS_CH1':'median_sls_price_houses_sold_US_CH1',
'MSPUS_PCH':'median_sls_price_houses_sold_US_PCH',
'MSPUS_PC1':'median_sls_price_houses_sold_US_PC1',
'MSPUS_PCA':'median_sls_price_houses_sold_US_PCA',
'MSPUS_CCH':'median_sls_price_houses_sold_US_CCH',
'MSPUS_CCA':'median_sls_price_houses_sold_US_CCA',
'MSPUS_LOG':'median_sls_price_houses_sold_US_LOG',
'NROU':'nat_rate_of_unemp_long_term',
'NROU_CHG':'nat_rate_of_unemp_long_term_CHG',
'NROU_CH1':'nat_rate_of_unemp_long_term_CH1',
'NROU_PCH':'nat_rate_of_unemp_long_term_PCH',
'NROU_PC1':'nat_rate_of_unemp_long_term_PC1',
'NROU_PCA':'nat_rate_of_unemp_long_term_PCA',
'NROU_CCH':'nat_rate_of_unemp_long_term_CCH',
'NROU_CCA':'nat_rate_of_unemp_long_term_CCA',
'NROU_LOG':'nat_rate_of_unemp_long_term_LOG',
'PCEC':'personal_consumption_expenditures',
'PCEC_CHG':'personal_consumption_expenditures_CHG',
'PCEC_CH1':'personal_consumption_expenditures_CH1',
'PCEC_PCH':'personal_consumption_expenditures_PCH',
'PCEC_PC1':'personal_consumption_expenditures_PC1',
'PCEC_PCA':'personal_consumption_expenditures_PCA',
'PCEC_CCH':'personal_consumption_expenditures_CCH',
'PCEC_CCA':'personal_consumption_expenditures_CCA',
'PCEC_LOG':'personal_consumption_expenditures_LOG',
'TDSP':'hh_debt_service_pmts_as_pct_of_disp_personal_income',
'TDSP_CHG':'hh_debt_service_pmts_as_pct_of_disp_personal_income_CHG',
'TDSP_CH1':'hh_debt_service_pmts_as_pct_of_disp_personal_income_CH1',
'TDSP_PCH':'hh_debt_service_pmts_as_pct_of_disp_personal_income_PCH',
'TDSP_PC1':'hh_debt_service_pmts_as_pct_of_disp_personal_income_PC1',
'TDSP_PCA':'hh_debt_service_pmts_as_pct_of_disp_personal_income_PCA',
'TDSP_CCH':'hh_debt_service_pmts_as_pct_of_disp_personal_income_CCH',
'TDSP_CCA':'hh_debt_service_pmts_as_pct_of_disp_personal_income_CCA',
'TDSP_LOG':'hh_debt_service_pmts_as_pct_of_disp_personal_income_LOG'}

In [8]:
# Rename columns
df_rename = df_rename.rename(rename_map, axis=1)
df_rename.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 100 columns):
quarter                                                    332 non-null object
real_disp_pers_inc                                         289 non-null float64
real_disp_pers_inc_CCA                                     218 non-null float64
real_disp_pers_inc_CCH                                     218 non-null float64
real_disp_pers_inc_CH1                                     285 non-null float64
real_disp_pers_inc_CHG                                     288 non-null float64
real_disp_pers_inc_LOG                                     250 non-null float64
real_disp_pers_inc_PC1                                     285 non-null float64
real_disp_pers_inc_PCA                                     288 non-null float64
real_disp_pers_inc_PCH                                     288 non-null float64
personal_consumption_exp_excl_food_energy                  238 non-null float64
personal_consumption_exp_excl_food_energy_CCA              237 non-null float64
personal_consumption_exp_excl_food_energy_CCH              237 non-null float64
personal_consumption_exp_excl_food_energy_CH1              234 non-null float64
personal_consumption_exp_excl_food_energy_CHG              237 non-null float64
personal_consumption_exp_excl_food_energy_LOG              238 non-null float64
personal_consumption_exp_excl_food_energy_PC1              234 non-null float64
personal_consumption_exp_excl_food_energy_PCA              237 non-null float64
personal_consumption_exp_excl_food_energy_PCH              237 non-null float64
cpi_US_total                                               238 non-null float64
cpi_US_total_CCA                                           230 non-null float64
cpi_US_total_CCH                                           230 non-null float64
cpi_US_total_CH1                                           234 non-null float64
cpi_US_total_CHG                                           237 non-null float64
cpi_US_total_LOG                                           233 non-null float64
cpi_US_total_PC1                                           234 non-null float64
cpi_US_total_PCA                                           237 non-null float64
cpi_US_total_PCH                                           237 non-null float64
DPCERO1Q156NBEA                                            286 non-null float64
DPCERO1Q156NBEA_CCA                                        261 non-null float64
DPCERO1Q156NBEA_CCH                                        261 non-null float64
DPCERO1Q156NBEA_CH1                                        282 non-null float64
DPCERO1Q156NBEA_CHG                                        285 non-null float64
DPCERO1Q156NBEA_LOG                                        269 non-null float64
DPCERO1Q156NBEA_PC1                                        281 non-null float64
DPCERO1Q156NBEA_PCA                                        284 non-null float64
DPCERO1Q156NBEA_PCH                                        284 non-null float64
tot_public_debt_as_pct_of_gdp                              214 non-null float64
tot_public_debt_as_pct_of_gdp_CCA                          213 non-null float64
tot_public_debt_as_pct_of_gdp_CCH                          213 non-null float64
tot_public_debt_as_pct_of_gdp_CH1                          210 non-null float64
tot_public_debt_as_pct_of_gdp_CHG                          213 non-null float64
tot_public_debt_as_pct_of_gdp_LOG                          214 non-null float64
tot_public_debt_as_pct_of_gdp_PC1                          210 non-null float64
tot_public_debt_as_pct_of_gdp_PCA                          213 non-null float64
tot_public_debt_as_pct_of_gdp_PCH                          213 non-null float64
gross_private_domestic_invest                              290 non-null float64
gross_private_domestic_invest_CCA                          289 non-null float64
gross_private_domestic_invest_CCH                          289 non-null float64
gross_private_domestic_invest_CH1                          286 non-null float64
gross_private_domestic_invest_CHG                          289 non-null float64
gross_private_domestic_invest_LOG                          290 non-null float64
gross_private_domestic_invest_PC1                          286 non-null float64
gross_private_domestic_invest_PCA                          289 non-null float64
gross_private_domestic_invest_PCH                          289 non-null float64
M2_velocity                                                242 non-null float64
M2_velocity_CCA                                            241 non-null float64
M2_velocity_CCH                                            241 non-null float64
M2_velocity_CH1                                            238 non-null float64
M2_velocity_CHG                                            241 non-null float64
M2_velocity_LOG                                            242 non-null float64
M2_velocity_PC1                                            238 non-null float64
M2_velocity_PCA                                            241 non-null float64
M2_velocity_PCH                                            241 non-null float64
median_sls_price_houses_sold_US                            227 non-null float64
median_sls_price_houses_sold_US_CCA                        226 non-null float64
median_sls_price_houses_sold_US_CCH                        226 non-null float64
median_sls_price_houses_sold_US_CH1                        223 non-null float64
median_sls_price_houses_sold_US_CHG                        226 non-null float64
median_sls_price_houses_sold_US_LOG                        227 non-null float64
median_sls_price_houses_sold_US_PC1                        223 non-null float64
median_sls_price_houses_sold_US_PCA                        226 non-null float64
median_sls_price_houses_sold_US_PCH                        226 non-null float64
nat_rate_of_unemp_long_term                                324 non-null float64
nat_rate_of_unemp_long_term_CCA                            323 non-null float64
nat_rate_of_unemp_long_term_CCH                            323 non-null float64
nat_rate_of_unemp_long_term_CH1                            320 non-null float64
nat_rate_of_unemp_long_term_CHG                            323 non-null float64
nat_rate_of_unemp_long_term_LOG                            324 non-null float64
nat_rate_of_unemp_long_term_PC1                            320 non-null float64
nat_rate_of_unemp_long_term_PCA                            323 non-null float64
nat_rate_of_unemp_long_term_PCH                            323 non-null float64
personal_consumption_expenditures                          290 non-null float64
personal_consumption_expenditures_CCA                      289 non-null float64
personal_consumption_expenditures_CCH                      289 non-null float64
personal_consumption_expenditures_CH1                      286 non-null float64
personal_consumption_expenditures_CHG                      289 non-null float64
personal_consumption_expenditures_LOG                      290 non-null float64
personal_consumption_expenditures_PC1                      286 non-null float64
personal_consumption_expenditures_PCA                      289 non-null float64
personal_consumption_expenditures_PCH                      289 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income        158 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CCA    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CCH    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CH1    154 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CHG    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_LOG    158 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PC1    154 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PCA    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PCH    157 non-null float64
dtypes: float64(99), object(1)
memory usage: 259.5+ KB

In [9]:
df_rename.quarter.sort_values()[:10]

0    1947Q1
1    1947Q2
2    1947Q3
3    1947Q4
4    1948Q1
5    1948Q2
6    1948Q3
7    1948Q4
8    1949Q1
9    1949Q2
Name: quarter, dtype: object

In [10]:
df_rename.quarter.sort_values(ascending=False)[:10]

331    2029Q4
330    2029Q3
329    2029Q2
328    2029Q1
327    2028Q4
326    2028Q3
325    2028Q2
324    2028Q1
323    2027Q4
322    2027Q3
Name: quarter, dtype: object

In [17]:
df_rename['year'] = df_rename['quarter'].apply(lambda x: x[:4])

df_rename.head()

df_subset = df_rename[
    (df_rename['year'].astype(int) < 2020) & 
    (df_rename['quarter'] != '2019Q3') &
    (df_rename['quarter'] != '2019Q4')]
df_subset.tail()

,quarter,real_disp_pers_inc,real_disp_pers_inc_CCA,real_disp_pers_inc_CCH,real_disp_pers_inc_CH1,real_disp_pers_inc_CHG,real_disp_pers_inc_LOG,real_disp_pers_inc_PC1,real_disp_pers_inc_PCA,real_disp_pers_inc_PCH,...,hh_debt_service_pmts_as_pct_of_disp_personal_income,hh_debt_service_pmts_as_pct_of_disp_personal_income_CCA,hh_debt_service_pmts_as_pct_of_disp_personal_income_CCH,hh_debt_service_pmts_as_pct_of_disp_personal_income_CH1,hh_debt_service_pmts_as_pct_of_disp_personal_income_CHG,hh_debt_service_pmts_as_pct_of_disp_personal_income_LOG,hh_debt_service_pmts_as_pct_of_disp_personal_income_PC1,hh_debt_service_pmts_as_pct_of_disp_personal_income_PCA,hh_debt_service_pmts_as_pct_of_disp_personal_income_PCH,year
285,2018Q2,2.7,-375.3,-93.8,0.0,-4.2,1.0,0.0,-97.7,-60.9,...,9.701680,-1.3,-0.3,-0.257747,-0.031504,2.3,-2.6,-1.3,-0.3,2018
286,2018Q3,3.3,80.3,20.1,1.0,0.6,1.2,43.5,123.2,22.2,...,9.691628,-0.4,-0.1,-0.247451,-0.010052,2.3,-2.5,-0.4,-0.1,2018
287,2018Q4,2.8,-65.7,-16.4,-0.9,-0.5,1.0,-24.3,-48.2,-15.2,...,9.741203,2.0,0.5,-0.134892,0.049575,2.3,-1.4,2.1,0.5,2018
288,2019Q1,4.5,189.8,47.4,-2.4,1.7,1.5,-34.8,567.1,60.7,...,9.710218,-1.3,-0.3,-0.022966,-0.030985,2.3,-0.2,-1.3,-0.3,2019
289,2019Q2,2.4,-251.4,-62.9,-0.3,-2.1,0.9,-11.1,-91.9,-46.7,...,9.687619,-0.9,-0.2,-0.014061,-0.022599,2.3,-0.1,-0.9,-0.2,2019

In [18]:
df_subset.info(verbose=True, null_counts=True)

# 290 possible values from 1947Q1 to 2019Q2

<class 'pandas.core.frame.DataFrame'>
Int64Index: 290 entries, 0 to 289
Data columns (total 101 columns):
quarter                                                    290 non-null object
real_disp_pers_inc                                         289 non-null float64
real_disp_pers_inc_CCA                                     218 non-null float64
real_disp_pers_inc_CCH                                     218 non-null float64
real_disp_pers_inc_CH1                                     285 non-null float64
real_disp_pers_inc_CHG                                     288 non-null float64
real_disp_pers_inc_LOG                                     250 non-null float64
real_disp_pers_inc_PC1                                     285 non-null float64
real_disp_pers_inc_PCA                                     288 non-null float64
real_disp_pers_inc_PCH                                     288 non-null float64
personal_consumption_exp_excl_food_energy                  238 non-null float64
personal_consumption_exp_excl_food_energy_CCA              237 non-null float64
personal_consumption_exp_excl_food_energy_CCH              237 non-null float64
personal_consumption_exp_excl_food_energy_CH1              234 non-null float64
personal_consumption_exp_excl_food_energy_CHG              237 non-null float64
personal_consumption_exp_excl_food_energy_LOG              238 non-null float64
personal_consumption_exp_excl_food_energy_PC1              234 non-null float64
personal_consumption_exp_excl_food_energy_PCA              237 non-null float64
personal_consumption_exp_excl_food_energy_PCH              237 non-null float64
cpi_US_total                                               238 non-null float64
cpi_US_total_CCA                                           230 non-null float64
cpi_US_total_CCH                                           230 non-null float64
cpi_US_total_CH1                                           234 non-null float64
cpi_US_total_CHG                                           237 non-null float64
cpi_US_total_LOG                                           233 non-null float64
cpi_US_total_PC1                                           234 non-null float64
cpi_US_total_PCA                                           237 non-null float64
cpi_US_total_PCH                                           237 non-null float64
DPCERO1Q156NBEA                                            286 non-null float64
DPCERO1Q156NBEA_CCA                                        261 non-null float64
DPCERO1Q156NBEA_CCH                                        261 non-null float64
DPCERO1Q156NBEA_CH1                                        282 non-null float64
DPCERO1Q156NBEA_CHG                                        285 non-null float64
DPCERO1Q156NBEA_LOG                                        269 non-null float64
DPCERO1Q156NBEA_PC1                                        281 non-null float64
DPCERO1Q156NBEA_PCA                                        284 non-null float64
DPCERO1Q156NBEA_PCH                                        284 non-null float64
tot_public_debt_as_pct_of_gdp                              214 non-null float64
tot_public_debt_as_pct_of_gdp_CCA                          213 non-null float64
tot_public_debt_as_pct_of_gdp_CCH                          213 non-null float64
tot_public_debt_as_pct_of_gdp_CH1                          210 non-null float64
tot_public_debt_as_pct_of_gdp_CHG                          213 non-null float64
tot_public_debt_as_pct_of_gdp_LOG                          214 non-null float64
tot_public_debt_as_pct_of_gdp_PC1                          210 non-null float64
tot_public_debt_as_pct_of_gdp_PCA                          213 non-null float64
tot_public_debt_as_pct_of_gdp_PCH                          213 non-null float64
gross_private_domestic_invest                              290 non-null float64
gross_private_domestic_invest_CCA                          289 non-null float64
gross_private_domestic_invest_CCH                          289 non-null float64
gross_private_domestic_invest_CH1                          286 non-null float64
gross_private_domestic_invest_CHG                          289 non-null float64
gross_private_domestic_invest_LOG                          290 non-null float64
gross_private_domestic_invest_PC1                          286 non-null float64
gross_private_domestic_invest_PCA                          289 non-null float64
gross_private_domestic_invest_PCH                          289 non-null float64
M2_velocity                                                242 non-null float64
M2_velocity_CCA                                            241 non-null float64
M2_velocity_CCH                                            241 non-null float64
M2_velocity_CH1                                            238 non-null float64
M2_velocity_CHG                                            241 non-null float64
M2_velocity_LOG                                            242 non-null float64
M2_velocity_PC1                                            238 non-null float64
M2_velocity_PCA                                            241 non-null float64
M2_velocity_PCH                                            241 non-null float64
median_sls_price_houses_sold_US                            226 non-null float64
median_sls_price_houses_sold_US_CCA                        225 non-null float64
median_sls_price_houses_sold_US_CCH                        225 non-null float64
median_sls_price_houses_sold_US_CH1                        222 non-null float64
median_sls_price_houses_sold_US_CHG                        225 non-null float64
median_sls_price_houses_sold_US_LOG                        226 non-null float64
median_sls_price_houses_sold_US_PC1                        222 non-null float64
median_sls_price_houses_sold_US_PCA                        225 non-null float64
median_sls_price_houses_sold_US_PCH                        225 non-null float64
nat_rate_of_unemp_long_term                                282 non-null float64
nat_rate_of_unemp_long_term_CCA                            281 non-null float64
nat_rate_of_unemp_long_term_CCH                            281 non-null float64
nat_rate_of_unemp_long_term_CH1                            278 non-null float64
nat_rate_of_unemp_long_term_CHG                            281 non-null float64
nat_rate_of_unemp_long_term_LOG                            282 non-null float64
nat_rate_of_unemp_long_term_PC1                            278 non-null float64
nat_rate_of_unemp_long_term_PCA                            281 non-null float64
nat_rate_of_unemp_long_term_PCH                            281 non-null float64
personal_consumption_expenditures                          290 non-null float64
personal_consumption_expenditures_CCA                      289 non-null float64
personal_consumption_expenditures_CCH                      289 non-null float64
personal_consumption_expenditures_CH1                      286 non-null float64
personal_consumption_expenditures_CHG                      289 non-null float64
personal_consumption_expenditures_LOG                      290 non-null float64
personal_consumption_expenditures_PC1                      286 non-null float64
personal_consumption_expenditures_PCA                      289 non-null float64
personal_consumption_expenditures_PCH                      289 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income        158 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CCA    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CCH    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CH1    154 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CHG    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_LOG    158 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PC1    154 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PCA    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PCH    157 non-null float64
year                                                       290 non-null object
dtypes: float64(99), object(2)
memory usage: 231.1+ KB

In [19]:
# Check for null values
null_data = df_subset[df_subset.isnull().any(axis=1)]
null_data

,quarter,real_disp_pers_inc,real_disp_pers_inc_CCA,real_disp_pers_inc_CCH,real_disp_pers_inc_CH1,real_disp_pers_inc_CHG,real_disp_pers_inc_LOG,real_disp_pers_inc_PC1,real_disp_pers_inc_PCA,real_disp_pers_inc_PCH,...,hh_debt_service_pmts_as_pct_of_disp_personal_income,hh_debt_service_pmts_as_pct_of_disp_personal_income_CCA,hh_debt_service_pmts_as_pct_of_disp_personal_income_CCH,hh_debt_service_pmts_as_pct_of_disp_personal_income_CH1,hh_debt_service_pmts_as_pct_of_disp_personal_income_CHG,hh_debt_service_pmts_as_pct_of_disp_personal_income_LOG,hh_debt_service_pmts_as_pct_of_disp_personal_income_PC1,hh_debt_service_pmts_as_pct_of_disp_personal_income_PCA,hh_debt_service_pmts_as_pct_of_disp_personal_income_PCH,year
0,1947Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947
1,1947Q2,-3.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947
2,1947Q3,11.1,NaN,NaN,NaN,14.9,2.4,NaN,7180.4,-392.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947
3,1947Q4,-5.5,NaN,NaN,NaN,-16.6,NaN,NaN,-94.0,-149.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947
4,1948Q1,7.7,NaN,NaN,NaN,13.2,2.0,NaN,284.2,-240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1948
5,1948Q2,13.0,209.5,52.4,16.8,5.3,2.6,-442.1,712.5,68.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1948
6,1948Q3,6.7,-265.1,-66.3,-4.4,-6.3,1.9,-39.6,-92.9,-48.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1948
7,1948Q4,2.3,-427.7,-106.9,7.8,-4.4,0.8,-141.8,-98.6,-65.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1948
8,1949Q1,-7.6,NaN,NaN,-15.3,-9.9,NaN,-198.7,11821.8,-430.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1949
9,1949Q2,2.0,NaN,NaN,-11.0,9.6,0.7,-84.6,-99.5,-126.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1949
10,1949Q3,2.6,104.9,26.2,-4.1,0.6,1.0,-61.2,185.6,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1949
11,1949Q4,2.3,-49.0,-12.3,0.0,-0.3,0.8,0.0,-38.8,-11.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1949
12,1950Q1,34.6,1084.4,271.1,42.2,32.3,3.5,-555.3,5121351.3,1404.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1950
13,1950Q2,-1.2,NaN,NaN,-3.2,-35.8,NaN,-160.0,-100.0,-103.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1950
14,1950Q3,5.1,NaN,NaN,2.5,6.3,1.6,96.2,32525.4,-525.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1950
15,1950Q4,2.5,-285.2,-71.3,0.2,-2.6,0.9,8.7,-94.2,-51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1950
16,1951Q1,0.4,-733.0,-183.3,-34.2,-2.1,-0.9,-98.8,-99.9,-84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1951
17,1951Q2,9.2,1254.2,313.5,10.4,8.8,2.2,-866.7,27984000.0,2200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1951
18,1951Q3,4.6,-277.3,-69.3,-0.5,-4.6,1.5,-9.8,-93.8,-50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1951
19,1951Q4,-0.7,NaN,NaN,-3.2,-5.3,NaN,-128.0,-99.9,-115.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1951
20,1952Q1,-0.2,NaN,NaN,-0.6,0.5,NaN,-150.0,-99.3,-71.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1952
21,1952Q2,5.2,NaN,NaN,-4.0,5.4,1.6,-43.5,45697500.0,-2700.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1952
22,1952Q3,8.3,187.0,46.8,3.7,3.1,2.1,80.4,549.1,59.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1952
23,1952Q4,8.9,27.9,7.0,9.6,0.6,2.2,-1371.4,32.2,7.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1952
24,1953Q1,4.8,-247.0,-61.7,5.0,-4.1,1.6,-2500.0,-91.5,-46.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1953
25,1953Q2,5.3,39.6,9.9,0.1,0.5,1.7,1.9,48.6,10.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1953
26,1953Q3,-1.9,NaN,NaN,-10.2,-7.2,NaN,-122.9,-98.3,-135.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1953
27,1953Q4,-1.3,NaN,NaN,-10.2,0.6,NaN,-114.6,-78.1,-31.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1953
28,1954Q1,2.0,NaN,NaN,-2.8,3.3,0.7,-58.3,460.2,-253.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1954
29,1954Q2,0.4,-643.8,-160.9,-4.9,-1.6,-0.9,-92.5,-99.8,-80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,1990Q3,-0.1,NaN,NaN,-2.8,-2.9,NaN,-103.7,-100.0,-103.6,...,11.583131,-0.6,-0.2,-0.210746,-0.017529,2.4,-1.8,-0.6,-0.2,1990
175,1990Q4,-3.4,NaN,NaN,-6.8,-3.3,NaN,-200.0,133633500.0,3300.0,...,11.604449,0.7,0.2,-0.141230,0.021318,2.5,-1.2,0.7,0.2,1990
176,1991Q1,1.0,NaN,NaN,-2.1,4.4,0.0,-67.7,-99.3,-129.4,...,11.578032,-0.9,-0.2,-0.071118,-0.026417,2.4,-0.6,-0.9,-0.2,1991
177,1991Q2,3.0,439.4,109.9,0.2,2.0,1.1,7.1,8000.0,200.0,...,11.434237,-5.0,-1.2,-0.166423,-0.143795,2.4,-1.4,-4.9,-1.2,1991
217,2001Q2,-0.7,NaN,NaN,-5.2,-4.4,NaN,-115.6,-99.9,-118.9,...,12.383873,7.3,1.8,0.723932,0.222883,2.5,6.2,7.5,1.8,2001
218,2001Q3,9.6,NaN,NaN,4.9,10.3,2.3,104.3,3537370.1,-1471.4,...,12.323468,-2.0,-0.5,0.486843,-0.060405,2.5,4.1,-1.9,-0.5,2001
219,2001Q4,-5.0,NaN,NaN,-6.4,-14.6,NaN,-457.1,-92.6,-152.1,...,12.622859,9.6,2.4,0.559514,0.299391,2.5,4.6,10.1,2.4,2001
220,2002Q1,9.3,NaN,NaN,5.6,14.3,2.2,151.4,1096.9,-286.0,...,12.416701,-6.6,-1.6,0.255711,-0.206158,2.5,2.1,-6.4,-1.6,2002
222,2002Q3,-0.3,NaN,NaN,-9.9,-3.0,NaN,-103.1,-100.0,-111.1,...,12.377254,1.3,0.3,0.053786,0.040883,2.5,0.4,1.3,0.3,2002
223,2002Q4,2.4,NaN,NaN,7.4,2.7,0.9,-148.0,409500.0,-900.0,...,12.346926,-1.0,-0.2,-0.275933,-0.030328,2.5,-2.2,-1.0,-0.2,2002
232,2005Q1,-4.6,NaN,NaN,-6.5,-9.7,NaN,-342.1,-33.8,-190.2,...,12.558832,10.4,2.6,0.348691,0.321615,2.5,2.9,10.9,2.6,2005
233,2005Q2,3.9,NaN,NaN,-0.8,8.5,1.4,-17.0,-48.3,-184.8,...,12.560029,0.0,0.0,0.428007,0.001197,2.5,3.5,0.0,0.0,2005
246,2008Q3,-8.1,NaN,NaN,-8.5,-15.6,NaN,-2125.0,36.0,-208.0,...,12.874881,2.6,0.6,-0.201895,0.082816,2.6,-1.5,2.6,0.6,2008
247,2008Q4,3.5,NaN,NaN,3.2,11.6,1.3,1066.7,-96.5,-143.2,...,12.824806,-1.6,-0.4,-0.390582,-0.050075,2.6,-3.0,-1.5,-0.4,2008
248,2009Q1,-1.7,NaN,NaN,-2.8,-5.2,NaN,-254.5,-94.4,-148.6,...,12.755924,-2.2,-0.5,-0.379705,-0.068882,2.5,-2.9,-2.1,-0.5,2009
249,2009Q2,4.4,NaN,NaN,-3.1,6.1,1.5,-41.3,4387.6,-358.8,...,12.370505,-12.3,-3.1,-0.421560,-0.385419,2.5,-3.3,-11.5,-3.0,2009
250,2009Q3,-4.4,NaN,NaN,3.7,-8.8,NaN,-45.7,0.0,-200.0,...,12.235962,-4.4,-1.1,-0.638919,-0.134543,2.5,-5.0,-4.3,-1.1,2009
251,2009Q4,-0.1,NaN,NaN,-3.6,4.3,NaN,-102.9,-100.0,-97.7,...,11.962675,-9.0,-2.3,-0.862131,-0.273287,2.5,-6.7,-8.6,-2.2,2009
252,2010Q1,2.3,NaN,NaN,4.0,2.4,0.8,-235.3,27984000.0,-2400.0,...,11.681821,-9.5,-2.4,-1.074103,-0.280854,2.5,-8.4,-9.1,-2.3,2010
257,2011Q2,-0.9,NaN,NaN,-7.7,-5.0,NaN,-113.2,-99.8,-122.0,...,10.686568,-3.2,-0.8,-0.663567,-0.087088,2.4,-5.8,-3.2,-0.8,2011
258,2011Q3,1.8,NaN,NaN,-1.1,2.7,0.6,-37.9,1500.0,-300.0,...,10.577200,-4.1,-1.0,-0.566993,-0.109368,2.4,-5.1,-4.0,-1.0,2011
262,2012Q3,-2.8,NaN,NaN,-4.6,-6.5,NaN,-255.6,-67.2,-175.7,...,10.143950,2.6,0.7,-0.433250,0.066023,2.3,-4.1,2.6,0.7,2012
263,2012Q4,11.6,NaN,NaN,10.4,14.4,2.5,866.7,29357.8,-514.3,...,9.828265,-12.6,-3.2,-0.622009,-0.315685,2.3,-6.0,-11.9,-3.1,2012
264,2013Q1,-15.1,NaN,NaN,-22.8,-26.7,NaN,-296.1,187.1,-230.2,...,10.188552,14.4,3.6,-0.012043,0.360287,2.3,-0.1,15.5,3.7,2013
265,2013Q2,3.0,NaN,NaN,-0.7,18.1,1.1,-18.9,-99.8,-119.9,...,10.112273,-3.0,-0.8,0.034346,-0.076279,2.3,0.3,-3.0,-0.7,2013
272,2015Q1,4.6,-64.1,-16.0,-1.1,-0.8,1.5,-19.3,-47.3,-14.8,...,9.918526,2.5,0.6,-0.058879,0.062594,2.3,-0.6,2.6,0.6,2015
273,2015Q2,3.0,-171.0,-42.7,-2.6,-1.6,1.1,-46.4,-81.9,-34.8,...,9.910980,-0.3,-0.1,-0.002740,-0.007546,2.3,0.0,-0.3,-0.1,2015
274,2015Q3,3.0,0.0,0.0,-1.8,0.0,1.1,-37.5,0.0,0.0,...,9.951684,1.6,0.4,0.078156,0.040704,2.3,0.8,1.7,0.4,2015
277,2016Q2,-0.4,NaN,NaN,-3.4,-3.1,NaN,-113.3,-100.0,-114.8,...,9.997024,3.9,1.0,0.086044,0.097104,2.3,0.9,4.0,1.0,2016
278,2016Q3,1.8,NaN,NaN,-1.2,2.2,0.6,-40.0,40906.3,-550.0,...,10.059204,2.5,0.6,0.107520,0.062180,2.3,1.1,2.5,0.6,2016

In [22]:
null_data.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 177 entries, 0 to 278
Data columns (total 101 columns):
quarter                                                    177 non-null object
real_disp_pers_inc                                         176 non-null float64
real_disp_pers_inc_CCA                                     105 non-null float64
real_disp_pers_inc_CCH                                     105 non-null float64
real_disp_pers_inc_CH1                                     172 non-null float64
real_disp_pers_inc_CHG                                     175 non-null float64
real_disp_pers_inc_LOG                                     137 non-null float64
real_disp_pers_inc_PC1                                     172 non-null float64
real_disp_pers_inc_PCA                                     175 non-null float64
real_disp_pers_inc_PCH                                     175 non-null float64
personal_consumption_exp_excl_food_energy                  125 non-null float64
personal_consumption_exp_excl_food_energy_CCA              124 non-null float64
personal_consumption_exp_excl_food_energy_CCH              124 non-null float64
personal_consumption_exp_excl_food_energy_CH1              121 non-null float64
personal_consumption_exp_excl_food_energy_CHG              124 non-null float64
personal_consumption_exp_excl_food_energy_LOG              125 non-null float64
personal_consumption_exp_excl_food_energy_PC1              121 non-null float64
personal_consumption_exp_excl_food_energy_PCA              124 non-null float64
personal_consumption_exp_excl_food_energy_PCH              124 non-null float64
cpi_US_total                                               125 non-null float64
cpi_US_total_CCA                                           117 non-null float64
cpi_US_total_CCH                                           117 non-null float64
cpi_US_total_CH1                                           121 non-null float64
cpi_US_total_CHG                                           124 non-null float64
cpi_US_total_LOG                                           120 non-null float64
cpi_US_total_PC1                                           121 non-null float64
cpi_US_total_PCA                                           124 non-null float64
cpi_US_total_PCH                                           124 non-null float64
DPCERO1Q156NBEA                                            173 non-null float64
DPCERO1Q156NBEA_CCA                                        148 non-null float64
DPCERO1Q156NBEA_CCH                                        148 non-null float64
DPCERO1Q156NBEA_CH1                                        169 non-null float64
DPCERO1Q156NBEA_CHG                                        172 non-null float64
DPCERO1Q156NBEA_LOG                                        156 non-null float64
DPCERO1Q156NBEA_PC1                                        168 non-null float64
DPCERO1Q156NBEA_PCA                                        171 non-null float64
DPCERO1Q156NBEA_PCH                                        171 non-null float64
tot_public_debt_as_pct_of_gdp                              101 non-null float64
tot_public_debt_as_pct_of_gdp_CCA                          100 non-null float64
tot_public_debt_as_pct_of_gdp_CCH                          100 non-null float64
tot_public_debt_as_pct_of_gdp_CH1                          97 non-null float64
tot_public_debt_as_pct_of_gdp_CHG                          100 non-null float64
tot_public_debt_as_pct_of_gdp_LOG                          101 non-null float64
tot_public_debt_as_pct_of_gdp_PC1                          97 non-null float64
tot_public_debt_as_pct_of_gdp_PCA                          100 non-null float64
tot_public_debt_as_pct_of_gdp_PCH                          100 non-null float64
gross_private_domestic_invest                              177 non-null float64
gross_private_domestic_invest_CCA                          176 non-null float64
gross_private_domestic_invest_CCH                          176 non-null float64
gross_private_domestic_invest_CH1                          173 non-null float64
gross_private_domestic_invest_CHG                          176 non-null float64
gross_private_domestic_invest_LOG                          177 non-null float64
gross_private_domestic_invest_PC1                          173 non-null float64
gross_private_domestic_invest_PCA                          176 non-null float64
gross_private_domestic_invest_PCH                          176 non-null float64
M2_velocity                                                129 non-null float64
M2_velocity_CCA                                            128 non-null float64
M2_velocity_CCH                                            128 non-null float64
M2_velocity_CH1                                            125 non-null float64
M2_velocity_CHG                                            128 non-null float64
M2_velocity_LOG                                            129 non-null float64
M2_velocity_PC1                                            125 non-null float64
M2_velocity_PCA                                            128 non-null float64
M2_velocity_PCH                                            128 non-null float64
median_sls_price_houses_sold_US                            113 non-null float64
median_sls_price_houses_sold_US_CCA                        112 non-null float64
median_sls_price_houses_sold_US_CCH                        112 non-null float64
median_sls_price_houses_sold_US_CH1                        109 non-null float64
median_sls_price_houses_sold_US_CHG                        112 non-null float64
median_sls_price_houses_sold_US_LOG                        113 non-null float64
median_sls_price_houses_sold_US_PC1                        109 non-null float64
median_sls_price_houses_sold_US_PCA                        112 non-null float64
median_sls_price_houses_sold_US_PCH                        112 non-null float64
nat_rate_of_unemp_long_term                                169 non-null float64
nat_rate_of_unemp_long_term_CCA                            168 non-null float64
nat_rate_of_unemp_long_term_CCH                            168 non-null float64
nat_rate_of_unemp_long_term_CH1                            165 non-null float64
nat_rate_of_unemp_long_term_CHG                            168 non-null float64
nat_rate_of_unemp_long_term_LOG                            169 non-null float64
nat_rate_of_unemp_long_term_PC1                            165 non-null float64
nat_rate_of_unemp_long_term_PCA                            168 non-null float64
nat_rate_of_unemp_long_term_PCH                            168 non-null float64
personal_consumption_expenditures                          177 non-null float64
personal_consumption_expenditures_CCA                      176 non-null float64
personal_consumption_expenditures_CCH                      176 non-null float64
personal_consumption_expenditures_CH1                      173 non-null float64
personal_consumption_expenditures_CHG                      176 non-null float64
personal_consumption_expenditures_LOG                      177 non-null float64
personal_consumption_expenditures_PC1                      173 non-null float64
personal_consumption_expenditures_PCA                      176 non-null float64
personal_consumption_expenditures_PCH                      176 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income        45 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CCA    44 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CCH    44 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CH1    41 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CHG    44 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_LOG    45 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PC1    41 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PCA    44 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PCH    44 non-null float64
year                                                       177 non-null object
dtypes: float64(99), object(2)
memory usage: 141.0+ KB

NoneType

In [25]:
df_subset.to_csv('../resources/FRED_data.csv', index=False)

In [32]:
# Filter dataset to 1976Q3 - 2018Q1
df_subset_final = df_subset[
    ~(df_subset['year'].astype(int) < 1976) & 
    (df_rename['quarter'] != '1976Q1') &
    (df_rename['quarter'] != '1976Q2')
#     ~(df_subset['year'].astype(int) > 2018) & 
#     (df_rename['quarter'] != '2018Q2') &
#     (df_rename['quarter'] != '2018Q3') &
#     (df_rename['quarter'] != '2018Q4')
]
df_subset_final['quarter'].sort_values()

/Users/gfidanli/anaconda3/envs/python3_default/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """

118    1976Q3
119    1976Q4
120    1977Q1
121    1977Q2
122    1977Q3
123    1977Q4
124    1978Q1
125    1978Q2
126    1978Q3
127    1978Q4
128    1979Q1
129    1979Q2
130    1979Q3
131    1979Q4
132    1980Q1
133    1980Q2
134    1980Q3
135    1980Q4
136    1981Q1
137    1981Q2
138    1981Q3
139    1981Q4
140    1982Q1
141    1982Q2
142    1982Q3
143    1982Q4
144    1983Q1
145    1983Q2
146    1983Q3
147    1983Q4
        ...
260    2012Q1
261    2012Q2
262    2012Q3
263    2012Q4
264    2013Q1
265    2013Q2
266    2013Q3
267    2013Q4
268    2014Q1
269    2014Q2
270    2014Q3
271    2014Q4
272    2015Q1
273    2015Q2
274    2015Q3
275    2015Q4
276    2016Q1
277    2016Q2
278    2016Q3
279    2016Q4
280    2017Q1
281    2017Q2
282    2017Q3
283    2017Q4
284    2018Q1
285    2018Q2
286    2018Q3
287    2018Q4
288    2019Q1
289    2019Q2
Name: quarter, Length: 172, dtype: object

In [33]:
df_subset_final.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 172 entries, 118 to 289
Data columns (total 101 columns):
quarter                                                    172 non-null object
real_disp_pers_inc                                         172 non-null float64
real_disp_pers_inc_CCA                                     132 non-null float64
real_disp_pers_inc_CCH                                     132 non-null float64
real_disp_pers_inc_CH1                                     172 non-null float64
real_disp_pers_inc_CHG                                     172 non-null float64
real_disp_pers_inc_LOG                                     151 non-null float64
real_disp_pers_inc_PC1                                     172 non-null float64
real_disp_pers_inc_PCA                                     172 non-null float64
real_disp_pers_inc_PCH                                     172 non-null float64
personal_consumption_exp_excl_food_energy                  172 non-null float64
personal_consumption_exp_excl_food_energy_CCA              172 non-null float64
personal_consumption_exp_excl_food_energy_CCH              172 non-null float64
personal_consumption_exp_excl_food_energy_CH1              172 non-null float64
personal_consumption_exp_excl_food_energy_CHG              172 non-null float64
personal_consumption_exp_excl_food_energy_LOG              172 non-null float64
personal_consumption_exp_excl_food_energy_PC1              172 non-null float64
personal_consumption_exp_excl_food_energy_PCA              172 non-null float64
personal_consumption_exp_excl_food_energy_PCH              172 non-null float64
cpi_US_total                                               172 non-null float64
cpi_US_total_CCA                                           165 non-null float64
cpi_US_total_CCH                                           165 non-null float64
cpi_US_total_CH1                                           172 non-null float64
cpi_US_total_CHG                                           172 non-null float64
cpi_US_total_LOG                                           167 non-null float64
cpi_US_total_PC1                                           172 non-null float64
cpi_US_total_PCA                                           172 non-null float64
cpi_US_total_PCH                                           172 non-null float64
DPCERO1Q156NBEA                                            172 non-null float64
DPCERO1Q156NBEA_CCA                                        159 non-null float64
DPCERO1Q156NBEA_CCH                                        159 non-null float64
DPCERO1Q156NBEA_CH1                                        172 non-null float64
DPCERO1Q156NBEA_CHG                                        172 non-null float64
DPCERO1Q156NBEA_LOG                                        162 non-null float64
DPCERO1Q156NBEA_PC1                                        171 non-null float64
DPCERO1Q156NBEA_PCA                                        171 non-null float64
DPCERO1Q156NBEA_PCH                                        171 non-null float64
tot_public_debt_as_pct_of_gdp                              172 non-null float64
tot_public_debt_as_pct_of_gdp_CCA                          172 non-null float64
tot_public_debt_as_pct_of_gdp_CCH                          172 non-null float64
tot_public_debt_as_pct_of_gdp_CH1                          172 non-null float64
tot_public_debt_as_pct_of_gdp_CHG                          172 non-null float64
tot_public_debt_as_pct_of_gdp_LOG                          172 non-null float64
tot_public_debt_as_pct_of_gdp_PC1                          172 non-null float64
tot_public_debt_as_pct_of_gdp_PCA                          172 non-null float64
tot_public_debt_as_pct_of_gdp_PCH                          172 non-null float64
gross_private_domestic_invest                              172 non-null float64
gross_private_domestic_invest_CCA                          172 non-null float64
gross_private_domestic_invest_CCH                          172 non-null float64
gross_private_domestic_invest_CH1                          172 non-null float64
gross_private_domestic_invest_CHG                          172 non-null float64
gross_private_domestic_invest_LOG                          172 non-null float64
gross_private_domestic_invest_PC1                          172 non-null float64
gross_private_domestic_invest_PCA                          172 non-null float64
gross_private_domestic_invest_PCH                          172 non-null float64
M2_velocity                                                172 non-null float64
M2_velocity_CCA                                            172 non-null float64
M2_velocity_CCH                                            172 non-null float64
M2_velocity_CH1                                            172 non-null float64
M2_velocity_CHG                                            172 non-null float64
M2_velocity_LOG                                            172 non-null float64
M2_velocity_PC1                                            172 non-null float64
M2_velocity_PCA                                            172 non-null float64
M2_velocity_PCH                                            172 non-null float64
median_sls_price_houses_sold_US                            172 non-null float64
median_sls_price_houses_sold_US_CCA                        172 non-null float64
median_sls_price_houses_sold_US_CCH                        172 non-null float64
median_sls_price_houses_sold_US_CH1                        172 non-null float64
median_sls_price_houses_sold_US_CHG                        172 non-null float64
median_sls_price_houses_sold_US_LOG                        172 non-null float64
median_sls_price_houses_sold_US_PC1                        172 non-null float64
median_sls_price_houses_sold_US_PCA                        172 non-null float64
median_sls_price_houses_sold_US_PCH                        172 non-null float64
nat_rate_of_unemp_long_term                                172 non-null float64
nat_rate_of_unemp_long_term_CCA                            172 non-null float64
nat_rate_of_unemp_long_term_CCH                            172 non-null float64
nat_rate_of_unemp_long_term_CH1                            172 non-null float64
nat_rate_of_unemp_long_term_CHG                            172 non-null float64
nat_rate_of_unemp_long_term_LOG                            172 non-null float64
nat_rate_of_unemp_long_term_PC1                            172 non-null float64
nat_rate_of_unemp_long_term_PCA                            172 non-null float64
nat_rate_of_unemp_long_term_PCH                            172 non-null float64
personal_consumption_expenditures                          172 non-null float64
personal_consumption_expenditures_CCA                      172 non-null float64
personal_consumption_expenditures_CCH                      172 non-null float64
personal_consumption_expenditures_CH1                      172 non-null float64
personal_consumption_expenditures_CHG                      172 non-null float64
personal_consumption_expenditures_LOG                      172 non-null float64
personal_consumption_expenditures_PC1                      172 non-null float64
personal_consumption_expenditures_PCA                      172 non-null float64
personal_consumption_expenditures_PCH                      172 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income        158 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CCA    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CCH    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CH1    154 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_CHG    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_LOG    158 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PC1    154 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PCA    157 non-null float64
hh_debt_service_pmts_as_pct_of_disp_personal_income_PCH    157 non-null float64
year                                                       172 non-null object
dtypes: float64(99), object(2)
memory usage: 137.1+ KB

In [35]:
# Columns with high numbe rof missing
cols_to_drop= [
    'hh_debt_service_pmts_as_pct_of_disp_personal_income',
    'hh_debt_service_pmts_as_pct_of_disp_personal_income_CCA',
    'hh_debt_service_pmts_as_pct_of_disp_personal_income_CCH',
    'hh_debt_service_pmts_as_pct_of_disp_personal_income_CH1',
    'hh_debt_service_pmts_as_pct_of_disp_personal_income_CHG',
    'hh_debt_service_pmts_as_pct_of_disp_personal_income_LOG',
    'hh_debt_service_pmts_as_pct_of_disp_personal_income_PC1',
    'hh_debt_service_pmts_as_pct_of_disp_personal_income_PCA',
    'hh_debt_service_pmts_as_pct_of_disp_personal_income_PCH'
]
df_subset_final = df_subset_final.drop(columns=cols_to_drop)

KeyError: "['hh_debt_service_pmts_as_pct_of_disp_personal_income'\n 'hh_debt_service_pmts_as_pct_of_disp_personal_income_CCA'\n 'hh_debt_service_pmts_as_pct_of_disp_personal_income_CCH'\n 'hh_debt_service_pmts_as_pct_of_disp_personal_income_CH1'\n 'hh_debt_service_pmts_as_pct_of_disp_personal_income_CHG'\n 'hh_debt_service_pmts_as_pct_of_disp_personal_income_LOG'\n 'hh_debt_service_pmts_as_pct_of_disp_personal_income_PC1'\n 'hh_debt_service_pmts_as_pct_of_disp_personal_income_PCA'\n 'hh_debt_service_pmts_as_pct_of_disp_personal_income_PCH'] not found in axis"

In [37]:
cols_to_remove = ['DPCERO1Q156NBEA_LOG',
'real_disp_pers_inc_CCA',
'real_disp_pers_inc_CCH',
'real_disp_pers_inc_LOG',
'cpi_US_total_CCA',
'cpi_US_total_CCH',
'cpi_US_total_LOG',
'DPCERO1Q156NBEA_CCA',
'DPCERO1Q156NBEA_CCH',
'DPCERO1Q156NBEA_LOG',
'DPCERO1Q156NBEA_PC1',
'DPCERO1Q156NBEA_PCA',
'DPCERO1Q156NBEA_PCH']

df_subset_final = df_subset_final.drop(columns=cols_to_remove)

df_subset_final.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 172 entries, 118 to 289
Data columns (total 80 columns):
quarter                                          172 non-null object
real_disp_pers_inc                               172 non-null float64
real_disp_pers_inc_CH1                           172 non-null float64
real_disp_pers_inc_CHG                           172 non-null float64
real_disp_pers_inc_PC1                           172 non-null float64
real_disp_pers_inc_PCA                           172 non-null float64
real_disp_pers_inc_PCH                           172 non-null float64
personal_consumption_exp_excl_food_energy        172 non-null float64
personal_consumption_exp_excl_food_energy_CCA    172 non-null float64
personal_consumption_exp_excl_food_energy_CCH    172 non-null float64
personal_consumption_exp_excl_food_energy_CH1    172 non-null float64
personal_consumption_exp_excl_food_energy_CHG    172 non-null float64
personal_consumption_exp_excl_food_energy_LOG    172 non-null float64
personal_consumption_exp_excl_food_energy_PC1    172 non-null float64
personal_consumption_exp_excl_food_energy_PCA    172 non-null float64
personal_consumption_exp_excl_food_energy_PCH    172 non-null float64
cpi_US_total                                     172 non-null float64
cpi_US_total_CH1                                 172 non-null float64
cpi_US_total_CHG                                 172 non-null float64
cpi_US_total_PC1                                 172 non-null float64
cpi_US_total_PCA                                 172 non-null float64
cpi_US_total_PCH                                 172 non-null float64
DPCERO1Q156NBEA                                  172 non-null float64
DPCERO1Q156NBEA_CH1                              172 non-null float64
DPCERO1Q156NBEA_CHG                              172 non-null float64
tot_public_debt_as_pct_of_gdp                    172 non-null float64
tot_public_debt_as_pct_of_gdp_CCA                172 non-null float64
tot_public_debt_as_pct_of_gdp_CCH                172 non-null float64
tot_public_debt_as_pct_of_gdp_CH1                172 non-null float64
tot_public_debt_as_pct_of_gdp_CHG                172 non-null float64
tot_public_debt_as_pct_of_gdp_LOG                172 non-null float64
tot_public_debt_as_pct_of_gdp_PC1                172 non-null float64
tot_public_debt_as_pct_of_gdp_PCA                172 non-null float64
tot_public_debt_as_pct_of_gdp_PCH                172 non-null float64
gross_private_domestic_invest                    172 non-null float64
gross_private_domestic_invest_CCA                172 non-null float64
gross_private_domestic_invest_CCH                172 non-null float64
gross_private_domestic_invest_CH1                172 non-null float64
gross_private_domestic_invest_CHG                172 non-null float64
gross_private_domestic_invest_LOG                172 non-null float64
gross_private_domestic_invest_PC1                172 non-null float64
gross_private_domestic_invest_PCA                172 non-null float64
gross_private_domestic_invest_PCH                172 non-null float64
M2_velocity                                      172 non-null float64
M2_velocity_CCA                                  172 non-null float64
M2_velocity_CCH                                  172 non-null float64
M2_velocity_CH1                                  172 non-null float64
M2_velocity_CHG                                  172 non-null float64
M2_velocity_LOG                                  172 non-null float64
M2_velocity_PC1                                  172 non-null float64
M2_velocity_PCA                                  172 non-null float64
M2_velocity_PCH                                  172 non-null float64
median_sls_price_houses_sold_US                  172 non-null float64
median_sls_price_houses_sold_US_CCA              172 non-null float64
median_sls_price_houses_sold_US_CCH              172 non-null float64
median_sls_price_houses_sold_US_CH1              172 non-null float64
median_sls_price_houses_sold_US_CHG              172 non-null float64
median_sls_price_houses_sold_US_LOG              172 non-null float64
median_sls_price_houses_sold_US_PC1              172 non-null float64
median_sls_price_houses_sold_US_PCA              172 non-null float64
median_sls_price_houses_sold_US_PCH              172 non-null float64
nat_rate_of_unemp_long_term                      172 non-null float64
nat_rate_of_unemp_long_term_CCA                  172 non-null float64
nat_rate_of_unemp_long_term_CCH                  172 non-null float64
nat_rate_of_unemp_long_term_CH1                  172 non-null float64
nat_rate_of_unemp_long_term_CHG                  172 non-null float64
nat_rate_of_unemp_long_term_LOG                  172 non-null float64
nat_rate_of_unemp_long_term_PC1                  172 non-null float64
nat_rate_of_unemp_long_term_PCA                  172 non-null float64
nat_rate_of_unemp_long_term_PCH                  172 non-null float64
personal_consumption_expenditures                172 non-null float64
personal_consumption_expenditures_CCA            172 non-null float64
personal_consumption_expenditures_CCH            172 non-null float64
personal_consumption_expenditures_CH1            172 non-null float64
personal_consumption_expenditures_CHG            172 non-null float64
personal_consumption_expenditures_LOG            172 non-null float64
personal_consumption_expenditures_PC1            172 non-null float64
personal_consumption_expenditures_PCA            172 non-null float64
personal_consumption_expenditures_PCH            172 non-null float64
year                                             172 non-null object
dtypes: float64(78), object(2)
memory usage: 108.8+ KB

In [38]:
df_subset_final.to_csv('../resources/FRED_data.csv', index=False)